### ISSUE TITLE
Adapt object-fit, object-position by matching source

### ISSUE THREAD

**Issue by AndyOGo** [ResponsiveImagesCG/ri-usecases#62]
Hy there,

I would really need to be able to change the additional attributes applied to the `<img>` tag, in particular those are `object-fit`, `object-position` and `class`.

I need this especially for professional art direction and to compensate for focal points of different renditions.

Suppose the following markup:

````html
<picture>
  <source
    srcset="foo-sm.jpg, foo-sm@2.jpg x2"
    media="(min-width: 200px)"
    object-position="top center"
  />
  <source
    srcset="foo-md.jpg, foo-md@2.jpg x2"
    media="(min-width: 600px)"
    class="medium-addition-for-a-class"
  />
  <source
    srcset="foo-lg.jpg, foo-lg@2.jpg x2"
    media="(min-width: 900px)"
  />
  <img
    src="foo.jpg"
    srcset="foo@2.jpg x2"
    class="picture__img"
    alt="Foo image"
    object-fit="cover"
    object-position="center"
  />
</picture>
````

**Comment by eeeps** [comment]
Can't/shouldn't you do this in CSS?

```css
.picture__img {
	object-fit: cover;
	object-position: center;
}

@media (min-width: 200px) and (max-width: 600px) {
	.picture__img {
		object-position: top center;
	}
}

@media (min-width: 600px) and (max-width: 900px) {
	.picture__img {
		/* whatever was going to apply to .medium-addition-for-a-class goes here */
	}
}
```
